### ISSUE TITLE
Check for compatibility with Panels

### ISSUE THREAD

**Issue by unbelievableflavour** [unbelievableflavour/Cotton#12]

**Comment by GuvBubbs** [comment]
Curse this idea! It's got be thinking now!
https://devblog.cadinbatrack.com/2022/03/02/panels-for-playdate/

**Comment by unbelievableflavour** [comment]
Checked compatibility with Panels. Unfortunately Panels is not currently setup for for use in other projects. Panels is a separate framework only useable as Panels. Hopefully that will change in the future!

**Comment by unbelievableflavour** [comment]
Ticket on the Panels repo had been closed with reason: out of scope. So for now it's out of scope. 

Closing this ticket As well.

**Comment by unbelievableflavour** [comment]
Experimental support is now added!
https://github.com/cadin/panels/issues/4#issuecomment-1236409057

Also created a wiki page for support:
https://github.com/unbelievableflavour/Cotton/wiki/How-to:-Integrate-Panels-(Beta)
