### ISSUE TITLE
Tiles are not rendered as collision when you have a big tileset

### ISSUE THREAD

**Issue by unbelievableflavour** [unbelievableflavour/Cotton#24]
When a tileset is bigger than 256 tiles; the colliders from the first 256 tiles will determine the collision of the second 256 tiles and third and so on.

**Comment by GuvBubbs** [comment]
Good luck with this one 😁

**Comment by unbelievableflavour** [comment]
**Dan's comment from the link above:** I have a fix for this that I think is looking good, we'll try to get it into the next SDK update!

**Comment by unbelievableflavour** [comment]
Fixed in 1.12.0!
