### ISSUE TITLE
Sync Entity's task

### ISSUE THREAD

**Issue by GuvBubbs** [unbelievableflavour/Cotton#27]
As someone coming from Pulp, the 9 step process to create an entity laid out here looks like a lot of work.

https://github.com/unbelievableflavour/Cotton/wiki/How-to:-Add-a-new-entity

I'd like to request a task / automation that reads the entity list from LDtk and does steps 4-8 for you.

**Comment by unbelievableflavour** [comment]
It's actually not a lot of work, and things are bound to be different from Pulp. You are not gonna get it simpler than this.
