### ISSUE TITLE
Sample project (without modification) crashes on start

### ISSUE THREAD

**Issue by Pvaiun** [unbelievableflavour/Cotton#29]
When uploaded to a playdate the sample project without modifications crashes on first update with the following callstack. Worth noting it works fine in the simulator.

_core/CoreGame.lua:215 attempt to index a nil value (field 'player')_

_stack traceback:_
_core/CoreGame.lua:215: in local 'fn'_
_core/lieb/call.lua:10 in function 'call'_
_core/lieb/scene.lua:119: in field 'update'_
_main.lua:31: in function <main.lua:28>_

**Apologies if I've done something wrong on my end and this is a known issue or user error, but I couldn't find another way to contact you to get a response. I'm super excited about this framework, it seems really awesome so far, and I just want to help!**

**Comment by unbelievableflavour** [comment]
Hi, since this might be a bug; this is probably the best location for it :)

Unfortunately I cannot test the issue myself since I still havent received my Playdate yet. I'll have a look when I receive it.

**Comment by unbelievableflavour** [comment]
Hi! So I have now retrieved my playdate :) and this bug is easily fixed by just enabling useFastLoader. 
FastLoader is required for Cotton to work on actual devices.
